### ISSUE TITLE
Рокетбанк не распознаёт переводы между своими счетами

### ISSUE THREAD

**Issue by timqzm** [zenmoney/ZenPlugins#149]
Задал вопрос саппорту, они не оч хотят чинить плагин:
http://support.zenmoney.ru/forums/1-podderzhka-dzen-mani/topics/866-roketbank-nadoel-sprashivat-parol-a-eschyo-on-ne-raspoznayot-perevodyi-mezhdu-schetami

И можно ли сделать так, чтобы пароль от Рокетбанковского приложения спрашивался не всякий раз? Или это ограничение накладывается самим банком?

@komex @skvav @Ryadnov (видел вас коммитах по Рокету; сам не шарю, сорян)

**Comment by komex** [comment]
У меня пароль от Рокетбанка спрашивается только если я заходил в официальное приложение. Если не заходить, то довольно долгое время никакого пароля спрашивать не будет, так как устройство привязывается к аккаунту.

По переводам - странно, по идее должен правильно их обрабатывать. Но это только в теории, так как у меня только один счёт и такой тип операций не тестировался.

Позже по ссылке отпишусь тоже.

**Comment by timqzm** [comment]
Хм, интересный момент, буду знать. Жалко, что в официальное приложение приходится часто заходить для разных переводов.

Я могу как-то помочь с тестированием, если нужно:)

**Comment by timqzm** [comment]
Зашёл в Дзен-мани, обновил историю. Рокет не спросил пароль (нечасто так бывает; мб, потому, что уже вводил его сегодня?).
Зашёл в приложение Рокета, сделал один перевод другу.
Опять зашёл в Дзен-мани, обновил историю.  Рокет опять **не** спросил пароль. Получил запись о переводе другу.

Может, это работает как-то иначе?

**Comment by skvav** [comment]
@timqzm если есть возможность прислать логи подключения к Рокету, то это помогло бы проверить что там с переводами. Логи отправить можно так: настройки подключения к Рокетбанку / Отправить лог разработчикам. Перед этим нужно провести синхронизацию с банком.

**Comment by komex** [comment]
@timqzm может что-то и поменялось. Ведь у них закрытое API и нет документации как таковой. Но у меня всегда после захода в мобильное приложение просит ввести пароль.

**Comment by timqzm** [comment]
@skvav кинул лог на почту саппорта
@komex затем ещё на твою, со скринами в качестве бонуса:)

**Comment by timqzm** [comment]
Переводы заработали, спасибо!

Если с паролем что-то реально сделать, было бы хорошо:)

**Comment by jonny3D** [comment]
Подключение к Рокетбанку переведено на новый API. Если будут замечания или вопросы, пожалуйста, пишите.

**Comment by komex** [comment]
Здравствуйте. Сегодня появилась ошибка [63] Заполните обязательные поля. Хотя раньше синхронизация работала отлично. Попытка заполнить данные по новой ничего не даёт - такая же ошибка. 12:18, 11 июня 2019 г., "Дмитрий" <notifications@github.com>:Подключение к Рокетбанку переведено на новый API. Если будут замечания или вопросы, пожалуйста, пишите.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
-- С уважением, Андрей Колченко

**Comment by jonny3D** [comment]
> Здравствуйте. Сегодня появилась ошибка [63] Заполните обязательные поля.

В этом случае нужно пересоздать подключение заново. Старое можно не удалять, оно обновится автоматически. Попробуйте, пожалуйста.

**Comment by komex** [comment]
Да, это помогло, спасибо. 22:33, 14 июня 2019 г., "Дмитрий" <notifications@github.com>:
Здравствуйте. Сегодня появилась ошибка [63] Заполните обязательные поля.

В этом случае нужно пересоздать подключение заново. Старое можно не удалять, оно обновится автоматически. Попробуйте, пожалуйста.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
-- С уважением, Андрей Колченко
