### ISSUE TITLE
[alfabank-by] Please install a new version of InSync to continue

### ISSUE THREAD

**Issue by OdNairy** [zenmoney/ZenPlugins#427]
Синхронизация с Альфа-Банк Беларусь перестала работать. Версия плагина 46. 
Я так понимаю, что стоит хайлайтнуть @vetheslav

**Comment by alparo** [comment]
Удваиваю! Та же проблема.
А до этого дважды лочило плагин в личном кабинете.
Слава, спасай!

**Comment by podabed** [comment]
I have the same problem.

**Comment by vetheslav** [comment]
Всем привет! К сожалению синхронизация Альфа-банка была временно отключена по просьбе самого банка. Но есть и хорошие новости, что ZenMoney подключится к официальному API для синхронизации всех операций. Это отличная новость, т.к. в таком случае сведутся на нет все корректировки, недочеты, недостаток информации по операциям и т.п. Но к сожалению нужно будет немного подождать.
О конкретных сроках лично я сообщить не могу, т.к. не являюсь разработчиком ZenMoney. Но я не думаю что эта интеграция слишком затянется во времени.
__________
Hey everyone! Unfortunately, the synchronizing with Alfa-Bank was disabled because of the Bank's request. But there's good news that ZenMoney is going to connect to official API to sync all the operations. It's great news because all the corrections and wrong information will be decreased. But we have to wait for a bit...
I can't tell you about deadlines because I'm not an official ZenMoney developer, but I hope and think the integration will be soon.

**Comment by skvav** [comment]
Official bank API is expected in first quarter of 2020. Until then, the plugin will be no more available by argreement with the bank.
